news:
    resource: "@newsBundle/Resources/config/routing.yml"
    prefix:   /

media:
    resource: "@MediaBundle/Resources/config/routing.yml"
    prefix:   /media

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /
 