# PHOTOS      
album_editer:
    pattern: /albums
    defaults: { _controller: SiteMediaBundle:Photo:photos }
    
photos:
    pattern:  /album/{id}
    defaults: { _controller: SiteMediaBundle:Photo:photos }
    requirements:
      id: \d+

photos_liste:
    pattern:  /photos/{id}
    defaults: { _controller: SiteMediaBundle:Photo:liste }
    requirements:
      id: \d+

album_supprimer:
    pattern:  /album/supprimer/{id}
    defaults: { _controller: SiteMediaBundle:Photo:supprimer }
    requirements:
      id: \d+

# albums_lien:
    # pattern:  /albums/
    # defaults: { _controller: SiteMediaBundle:Photo:photos }

commentaire_photos:
    pattern:  /photos/commentaires/{id}
    defaults: { _controller: SiteMediaBundle:Photos:commentaire }
    requirements:
      id: \d+

