parameters:
#    site_media.example.class: Site\MediaBundle\Example

services:
#    site_media.example:
#        class: %site_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
